default_language_version:
  python: python3
repos:
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'
    hooks:
      - id: vulture
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        exclude: ^.*/migrations/.*.py
        additional_dependencies: ['click<=8.0.4']
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
