# Generated by Django 4.1.5 on 2023-01-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
