# Generated by Django 4.1.3 on 2022-12-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="currency",
        ),
    ]
