# Generated by Django 4.1.3 on 2022-12-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        blank=True, choices=[("Borrow", "Borrow"), ("Lend", "Lend")], max_length=32, null=True
                    ),
                ),
                ("second_person", models.CharField(blank=True, max_length=254, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
