# Generated by Django 4.1.3 on 2022-12-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        blank=True, choices=[("BORROW", "BORROW"), ("LEND", "LEND")], max_length=32, null=True
                    ),
                ),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("partial_paid", models.BooleanField(default=False)),
                (
                    "partial_paid_amount",
                    models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
                ),
                ("second_person", models.CharField(blank=True, max_length=254, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
