# Generated by Django 4.1.3 on 2022-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("MDL", "MDL"), ("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")],
                max_length=3,
                null=True,
            ),
        ),
    ]
