# Generated by Django 4.1.3 on 2022-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0002_debt_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
