# Generated by Django 4.1.3 on 2022-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0003_alter_debt_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="partially_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="debt",
            name="partially_paid_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
