# Generated by Django 4.1.3 on 2022-12-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0004_debt_partially_paid_debt_partially_paid_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debt",
            old_name="partially_paid",
            new_name="partial_paid",
        ),
        migrations.RenameField(
            model_name="debt",
            old_name="partially_paid_amount",
            new_name="partial_paid_amount",
        ),
    ]
