# Generated by Django 4.1.3 on 2022-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0005_rename_partially_paid_debt_partial_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="partial_paid_amount",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
