# Generated by Django 4.1.3 on 2022-12-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_category_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="currency",
        ),
    ]
